# Generated by Django 4.0.3 on 2022-04-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0007_accessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads')),
                ('code', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
